name: Build "turnip"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: true
        type: string

jobs:
  start_building_turnip:
    runs-on: ubuntu-24.04
    env:
      BUILD_VERSION: ${{ inputs.version }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - uses: actions/checkout@v4

    - name: Prepare environment
      run: |
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
        sudo apt update
        sudo apt install -y build-essential flex bison glslang-tools
        sudo apt install -y meson-1.5

    - name: Execute build script
      run: bash ./turnip_builder.sh

    - name: List files in /tmp
      run: ls -la /tmp/*.zip || echo "No zip files found"

    - name: Release "turnip"
      uses: softprops/action-gh-release@v2
      with:
        tag_name: tu_v${{ inputs.version }}
        name: Turnip A8XX_T v${{ inputs.version }}
        body: |
          Turnip TU8 — Fork of whitebelyashx’s Repository with Adreno 8XX Patches

          This release is a custom fork of the original work by whitebelyashx, extended with additional patches and optimizations specifically targeted at Adreno 810.
          The build is still in beta testing, and stability may vary depending on the device.
          Please do not report any issues to Mesa, as this is an unofficial fork.

          🖥 Supported GPU
          
          • Adreno 840/830 — maybe they work
          • Adreno 810 — sysmem/gmem, tested, includes custom patches.
          • Adreno 829/825 — They may work, but not guaranteed.

          📝 Changes
          

          ⚠️ Notes
          • If you see black artifacts, disable DXVK_HUD=0
          • Eden and some emulators may require higher render scale
          • If unstable: TU_DEBUG=nolrz
          • For sysmem mode: export TU_DEBUG=sysmem

        files: |
          /tmp/A8XX_T-V${{ inputs.version }}.zip
