name: Build Turnip

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      BUILD_VERSION: ${{ inputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential flex bison zip unzip curl \
            meson ninja-build python3-pip \
            glslang-tools

      - name: Build
        run: bash ./turnip_builder.sh

      - name: Show files (debug)
        run: ls -lah output

      - name: Upload artifact (backup)
        uses: actions/upload-artifact@v4
        with:
          name: turnip-build
          path: output/*.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: tu_y${{ inputs.version }}
          name: A8XX_Y${{ inputs.version }}
          files: output/*.zip
          body: |
            A8XX Turnip Vulkan V${{ inputs.version }}
            Built from: https://github.com/DiskDVD/mesa-tu8

            Turnip TU8 — Fork of whitebelyashx's Repository with Adreno 8XX Patches

            This release is a custom fork of the original work by whitebelyashx, extended with additional patches and optimizations specifically targeted at Adreno 810/829.
            The build is still in beta testing, and stability may vary depending on the device.
            Please do not report any issues to Mesa, as this is an unofficial fork.

            💿 Interlayer:
            1) proton-10arm64ec or proton-11arm64ec
            2) Rendering mode: DXVK 2.4.1 or newer / VKD3D 2.14 or newer
            3) Memory type: Autotuner or sysmem
            4) Permission: Depends on the game

            🖥 Supported GPU:
            • Adreno 840 — working
            • Adreno 830 — recommended sysmem
            • Adreno 829/825 — fully working
            • Adreno 810 — fully working

            Notes:
            - A810/829 have exclusive patches
            - For RDR2 on A810/829 use: TU_DEBUG = nolrz

            Changes:
            - Initial release / improvements / fixes

            Credits:
            whitebelyash (Main developer)
            DerixSpace
            Lebron
            Whitedevil2427
            Ikol5v
            Michael
            Driver community

            Contacts:
            Telegram: @DISK_DVD
            Discord: EmuCore
